spring:
  application:
    name: payment-service
  liquibase:
    change-log: db/changelog/master.yaml
    enabled: true
    driver-class-name: liquibase.ext.mongodb.database.MongoClientDriver
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST:localhost:27017}/${MONGO_DATABASE}?authSource=admin
kafka:
  bootstrap-servers: kafka-0:9090,kafka-1:9090,kafka-2:9090
  producer:
    topics:
      payment-created:
        name: PAYMENT_CREATED
        partitions: 6
        replicas: 3
        min-insync: 2
    acks: all
    request-timeout: 5000
    enable-idempotence: true
  consumer:
    group-id: payment-service
    trusted-packages: com.innowise.orderservice.event
    allow-auto-create-topics: false
random-number-api:
  url: http://www.randomnumberapi.com/api/v1.0/random?min=0&max=2&count=1
logging:
  level:
    com.innowise: ${APP_LOGGING_LEVEL:info}
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/